
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: sba-course
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:32002/sba_course?useSSL=true
    username: root
    password: 123456
server:
  servlet:
    context-path: /course
  port: 9996
 

logging:
 level: 
  com:
   sba:
    course:
     mapper: Debug  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
#        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true
  
---
spring:
  profiles: k8s
  application:
    name: sba-course
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sba-course-db:3306/sba_course?useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:
  servlet:
    context-path: /course
  port: 9996
  
eureka:
  client:
    service-url:
      defaultZone: http://sba-registry:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
#        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true

