apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-account
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sba-account
  template:
    metadata:
      labels:
        app: sba-account
    spec:
      containers:
        - name: sba-account
          image: registry.cn-shanghai.aliyuncs.com/yuanbing/sba-account:{version}
          ports:
            - name: http-port
              containerPort: 9996
          env:
            - name: spring_profiles_active
              value: k8s
      imagePullSecrets:
        - name: sba